name: zemoga_posts
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  posts_api_client:
    path: packages/posts_api_client
  posts_repository:
    path: packages/posts_repository
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  bloc_test: ^9.1.0
  pretty_dio_logger: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

fonts:
  - family: PoppinsRegular
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  - family: PoppinsLight
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
  - family: PoppinsMedium
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  - family: PoppinsBold
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
